name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  sync:
    name: Sync repositories
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - uses: actions/checkout@v2
      - run: |
             git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Sync terraform providers
        run: |
              cd schemas-extractor
              export GOPATH=/tmp/
              make
              cp -r schemas/* ../terraform/model/
              cp providers.list ../terraform/model

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: latest-sync
          path: terraform
          retention-days: 5

  commit-results:
    name: Commit results
    runs-on: ubuntu-latest
    needs: [sync]
    steps:
      - uses: actions/checkout@v2
      - run: |
             git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Fetch artifacts
        uses: actions/download-artifact@v1
        with:
          name: latest-sync

      - name: Apply latest artifact
        run: |
              sudo apt update
              git status
              rsync -a latest-sync/ terraform/
              rm -rf latest-sync
              git status

      - name: Set commit message
        id: commit
        run: |
              echo "::set-output name=desc::Update metadata as of  $(date)"

      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: ${{ steps.commit.outputs.desc }}
          branch: sync
          commit_user_name: Vladimir Samoylov
          commit_user_email: cageyv.dev@gmail.com

      - name: Merge sync changes to master
        run: |
              git status
              git checkout master
              if [ "`git branch --list sync`" ]; then git cherry-pick sync && git push; fi
